// Synthetic demo feedback — used when the PM clicks "Try with sample data".
// Deliberately mixes clear enterprise-readiness signals with unrelated asks
// so the AI clustering has real work to do.

export const DEMO_FEEDBACK: string[] = [
  "We can't roll this out company-wide until you support SSO with Okta. Security won't approve otherwise.",
  "Any timeline on SAML? Our IT team blocked the pilot because we can't provision through our IdP.",
  "Need SCIM provisioning — manually adding 400 users is a non-starter for us.",
  "Our infosec review flagged that you don't have SOC 2 Type II. That's a hard requirement for us to renew.",
  "When will you be SOC 2 compliant? Our procurement team asked and I had no answer.",
  "We'd need a private VPC deployment option for our regulated workloads. Multi-tenant is a dealbreaker for legal.",
  "Do you offer a self-hosted or on-prem version? Our data can't leave our network.",
  "Please add audit logs I can export to our SIEM. Compliance is asking every quarter.",
  "We need role-based permissions. Right now everyone in the workspace sees everything, which is a problem.",
  "Enterprise SSO + audit log export would unblock our 200-seat rollout tomorrow.",
  "The mobile app crashes every time I try to open a large document. iPhone 15, latest iOS.",
  "Mobile is basically unusable. It hangs for 30+ seconds on load and I have to force-quit.",
  "Please fix the iOS app — I can't respond to comments on the go without it freezing.",
  "The Android app is missing half the features the web app has. When is parity coming?",
  "Mobile push notifications don't work reliably. I miss urgent mentions.",
  "Search is terrible. I know a doc exists but I can never find it with your search.",
  "Full-text search across all my workspaces would save me so much time.",
  "The search doesn't seem to index attachments or PDFs, which is where most of our content lives.",
  "Can you add filters to search? Filtering by author and date range would be huge.",
  "Fuzzy search / typo tolerance please. If I misspell one letter I get zero results.",
  "I love the product overall — the writing experience is really clean and fast.",
  "The onboarding flow was surprisingly smooth. Got my team up and running in a day.",
  "Pricing feels a bit steep for smaller teams but I understand the value.",
  "Would love a native Linux desktop app. Web works but eats RAM.",
  "The API rate limits are too aggressive for our automation. Can we get a higher tier?",
  "Webhooks would let us integrate with our internal tools much more cleanly than polling.",
  "The Zapier integration is missing key triggers — specifically 'new comment' events.",
  "Real-time collaboration sometimes drops changes when two people edit the same paragraph.",
  "Offline mode would be amazing — I travel a lot and lose progress when the connection drops.",
  "AI writing assist is nice but it hallucinates references. I'd rather it just not cite than cite something fake.",
];
